name: CI Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  issue_comment:
    types:
      - created

jobs:
  golang-ci:
    # Use a released version for stable.
    uses: kerthcet/github-workflow-as-kube/.github/workflows/workflow-golang-ci.yaml@main
