name: Workflow As Kubernetes

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  event-handler:
    # Use a released version for stable.
    uses: kerthcet/github-workflow-as-kube/.github/workflows/workflow-as-kubernetes.yaml@main
    secrets:
      AGENT_TOKEN: ${{ secrets.AGENT_TOKEN }}
