name: Workflow As Kubernetes Initialization

on:
  workflow_dispatch:

jobs:
  call-workflow:
    # Use a released version for stable.
    uses: kerthcet/github-workflow-as-kube/.github/workflows/workflow-as-kubernetes-init.yaml@main
    secrets:
      AGENT_TOKEN: ${{ secrets.AGENT_TOKEN }}
