name: Workflow As Kubernetes

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  call-workflow:
    uses: ../../workflows/kube-workflow.yaml@main
    secrets:
      AGENT_TOKEN: ${{ secrets.AGENT_TOKEN }}
