name: Publish Helm Chart

on:
  workflow_call:
    secrets:
      AGENT_TOKEN:
        required: true
    inputs:
      repo_url:
        description: 'repo url'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.0

    - name: Cache Helm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/helm
        key: ${{ runner.os }}-helm-${{ hashFiles('**/Chart.yaml') }}
        restore-keys: |
          ${{ runner.os }}-helm

    - name: Package Helm Chart
      run: helm package ./chart -d ./helm-packages

    - name: Create Helm Repo Index
      run: helm repo index ./helm-packages --url ${{ inputs.repo_url }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.AGENT_TOKEN }}
        publish_dir: ./helm-packages
