name: Workflow As Kubernetes Initialization

on:
  workflow_call:
    secrets:
      AGENT_TOKEN:
        required: true

env:
  GH_TOKEN: ${{ secrets.AGENT_TOKEN }}

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Register required labels
      run: |
        # All needs-xxx should use #EDEDED.

        gh label create "feature" --color 1D76DB --description "Categorizes issue or PR as related to a new feature." --force
        gh label create "cleanup" --color 1D76DB --description "Categorizes issue or PR as related to cleaning up code, process, or technical debt." --force
        gh label create "bug" --color B60205 --description "Categorizes issue or PR as related to a bug." --force
        gh label create "documentation" --color 1D76DB --description "Categorizes issue or PR as related to documentation." --force

        gh label create "lgtm" --color 0E8A16 --description "Looks good to me, indicates that a PR is ready to be merged." --force
        gh label create "approved" --color 0E8A16 --description "Indicates a PR has been approved by an approver from all required OWNERS files." --force

        gh label create "do-not-merge/hold" --color 006B75 --description "Indicates that a PR should not merge because someone has issued a /hold command." --force

        gh label create "needs-priority" --color EDEDED --description "Indicates a PR lacks a `priority/foo` label and requires one." --force
        gh label create "important-critical-urgent" --color ff7500 --description "Highest priority. Must be actively worked on as someone's top priority right now." --force
        gh label create "important-soon" --color ff8936 --description "Must be staffed and worked on either currently, or very soon, ideally in time for the next release." --force
        gh label create "important-longterm" --color fa8c35 --description "Important over the long term, but may not be staffed and/or may need multiple releases to complete." --force
        gh label create "backlog" --color ffa631 --description "Higher priority than priority/awaiting-more-evidence." --force
        gh label create "awaiting-more-evidence" --color ffa400 --description "Lowest priority. Possibly useful, but not yet enough support to actually get it done." --force
