name: Workflow for Golang CI

on:
  workflow_call:

env:
  GO_VERSION: "1.23.0"
  GOLANGCI_VERSION: "1.63.4"
  CGO_ENABLED: "0"

jobs:
  golang-ci:
    if: (github.event_name == 'issue_comment' && github.event.comment.body == '/retest') || github.event_name == 'pull_request'
    name: golang-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v${{ env.GOLANGCI_VERSION }}
          args: --timeout=30m --config=.golangci.yaml

  unit-test:
    if: (github.event_name == 'issue_comment' && github.event.comment.body == '/retest') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          make test

  integration-test:
    if: (github.event_name == 'issue_comment' && github.event.comment.body == '/retest') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run integration tests
        run: |
          make test-integration

  e2e-test:
    if: (github.event_name == 'issue_comment' && github.event.comment.body == '/retest') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run e2e tests
        run: |
          make test-e2e
