name: Workflow for Golang CI

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.24.1"
  # Do not add the 'v' prefix to the golangci-lint version.
  GOLANGCI_VERSION: "2.2.1"
  CGO_ENABLED: "0"

jobs:
  golang-lint:
    name: golang-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v${{ env.GOLANGCI_VERSION }}
          args: --timeout=30m --config=.golangci.yaml

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          make test

  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run integration tests
        run: |
          make test-integration

  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run e2e tests
        run: |
          make test-e2e
